project:
  type: book
  output-dir: _book
  # preview:
  #   port: 4200
  #   browser: false

language: _lang_es.yml

book:
  title: "Introducci贸n a la Rob贸tica"
  # author: "Oscar E. Ramos Ponce"
  # date: "1/25/2023"

  reader-mode: true

  page-footer:
    left: |
      Copyright 2023, Oscar E. Ramos. Todos los derechos reservados.
    right: |
      Introducci贸n a la Rob贸tica - Oscar E. Ramos
  
  site-url: index.qmd

  chapters:
    - index.qmd
    - conceptos_introductorios.qmd
    - cr_posicion_orientacion.qmd
    - cr_parametrizaciones_orientacion.qmd
    - referencias.qmd
  appendices:
    - ap_elementos_matematicos.qmd
    - ap_cuaterniones.qmd

bibliography: referencias.bib

execute:
  freeze: auto
  
format:
  html:
    theme:
      - cosmo
      - _bookstyle.scss
    code-link: true
    author-meta: "Oscar E. Ramos Ponce"
  # pdf:
  #   documentclass: scrreprt
